# List of paths to exclude from linting
excluded:
  - docs
  - Documentation
  - Scripts
  - .github  

# Rules run by SwiftLint's analyzer, more computationally intensive
analyzer_rules:
  - capture_variable # Warns about variables captured by closures that could lead to retain cycles
  - unused_import # Detects unused import statements

# Rules that are disabled
disabled_rules:
  - todo # TODO comments
  - multiple_closures_with_trailing_closure # Multiple trailing closures in a function call
  - trailing_whitespace
  - nslocalizedstring_key
  - convenience_type

# Rules that are not enabled by default but are opted into
opt_in_rules:
  - object_literal # Prefer object literals over the corresponding constructors
  - nslocalizedstring_key # Enforce use of NSLocalizedString
  - yoda_condition # Conditions should not be written in Yoda condition style
  - overridden_super_call # Check if super methods are called when overridden
  - prefer_zero_over_explicit_init # Prefer .zero over explicit init for types that conform to ZeroInitializable
  - single_test_class # Single class should be contained within a test case
  - static_operator # Static operators are preferred in type method implementations
  - control_statement # Enforce braces in control statements
  - empty_count # Prefer isEmpty over checking count == 0
  - trailing_newline # Files should have a single trailing newline
  - colon # Ensure colons follow the variable/type, not spaced
  - comma # Ensure no space before and one after any comma
  - sorted_imports # Imports should be sorted
  - missing_docs # Public entities should be documented
  - convenience_type # Types used for convenience and not for polymorphism should be enums
  - multiline_parameters # Enforce function parameters to be either on the same line, or one per line
  - vertical_parameter_alignment # Align parameters vertically
  - vertical_parameter_alignment_on_call # Align parameters vertically on call
  - vertical_whitespace_closing_braces # No vertical whitespace before closing braces
  - vertical_whitespace_opening_braces # No vertical whitespace after opening braces
  - redundant_type_annotation # Avoid redundant type annotations
  - sorted_first_last # Prefer .first over [0] and .last over [count - 1]
  - explicit_init # Prefer explicit init call
  - file_header # Custom rule to avoid author information in file headers

# Treat all warnings as errors
strict: true

# Configuration for the identifier name rule
identifier_name:
  excluded:
    - id # Excludes 'id' from being flagged

# Configuration for force casting
force_cast: error

# Configuration for force try
force_try:
  severity: error

# Limits on type body length
type_body_length:
  - 300 # Warning
  - 400 # Error

# Limits on file length
file_length:
  warning: 500
  error: 800
  
# Limits on line lenght
line_length:
  warning: 160
  error: 180
 

# Configuration for large tuples
large_tuple:
   - 4 # Warning for 3-value tuples
   - 5 # Error for 4-value tuples

# Configuration for missing documentation
missing_docs:
  excludes_inherited_types: false

# Configuration for type names
type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded: iPhone

# Limits on function parameter count
function_parameter_count:
  warning: 7

# Configuration for cyclomatic complexity
cyclomatic_complexity:
  warning: 16

# Configuration for nesting
nesting:
  type_level: 2
  function_level: 2

# Output format for SwiftLint warnings/errors
reporter: "xcode"
